<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDT_Cura_Login_Validation_TestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>31a410c7-bdc2-4a14-a395-28d1a7bec573</testSuiteGuid>
   <testCaseLink>
      <guid>08a9275a-0f05-42a6-8b06-8642359a1244</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CURA_Login_Validation_001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f6a8a835-b83a-4be1-a508-e89863a10644</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Cura_Test_data/Cura_H_Login_Test_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f6a8a835-b83a-4be1-a508-e89863a10644</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>b7f6b000-7728-4e46-9ad7-88cfb32c4965</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f6a8a835-b83a-4be1-a508-e89863a10644</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>87c2034d-652a-4ef7-a65a-27d2dfaf82f0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
